background {
    monitor = eDP-1
    path = /home/cosnate/backups/wallpapers/98.jpg
    blur_passes = 0
    contrast = 0
    brightness = 0
    vibrancy = 0
    vibrancy_darkness = 0
}

label {
    monitor = eDP-1

    text = cmd[update:1000] echo "$(date '+%H:%M')"
    color = rgba(255, 255, 255, 0.5)
    font_size = 20
    font_family = JetBrains Mono

    position = -100, -100
    halign = right
    valign = top
}

# label {
#     monitor = eDP-1
#
#     text = cmd[update:1000] echo "$(date '+%M')"
#     color = rgba(255, 255, 255, 0.7)
#     font_size = 120
#     font_family = JetBrains Mono Bold
#
#     position = 0, -65
#     halign = center
#     valign = center
# }

label {
    monitor = eDP-1

    text = cmd[update:60000] echo "$(date '+%A, %d %B')"
    color = rgba(255, 255, 255, 0.3)
    font_size = 10
    font_family = JetBrains Mono

    position = -100, -140
    halign = right
    valign = top
}

input-field {
    monitor = eDP-1
    size = 250, 40
    outline_thickness = 0
    dots_size = 0.1
    dots_spacing = 0.1
    dots_center = true
    inner_color = rgba(255, 255, 255, 0.05)
    font_color = rgba(255,255,255, 0.7)
    placeholder_text= ***
    fade_on_empty = false
    hide_input = false
    position = 0, 0
    halign = center
    valign = center
}
