background {
    monitor = eDP-1
    path = /home/cosnate/backups/wallpapers/98.jpg
    blur_passes = 0
    contrast = 0
    brightness = 0
    vibrancy = 0
    vibrancy_darkness = 0
}

input-field {
    monitor = eDP-1
    size = 250, 40
    outline_thickness = 0
    dots_size = 0.1
    dots_spacing = 0.1
    dots_center = true
    inner_color = rgba(255, 255, 255, 0.05)
    font_color = rgba(255,255,255, 0.5)
    placeholder_text=
    fade_on_empty = false
    hide_input = false
    halign = center
    valign = center
}
